name: Sync to Gitee

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/fallssyj'
          dst: 'gitee/falls_syj'
          src_token: ${{ secrets.GITHUB_TOKEN }}
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'PixSnap'
          force_update: true
